In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [19]:
## Initial Data
# Read the data from the csv
df = pd.read_csv("Trauma Data.csv")
# Drop rows that have null ti#s (Note: These are rows that have numerous ais 2005#s)
print(df.shape[0])
df = df.dropna(subset=['tid'])

# Rename columns
df = df.rename(columns={'injury_comments': 'Injury Comments'})
df = df.rename(columns={'levels': 'Levels'})
df = df.rename(columns={'feild_SBP': 'Field SBP'})
df = df.rename(columns={'feild_RR': 'Field RR', 'feild_HR': 'Field HR', 'feild_schok_ind': 'Shock Index', 'feild_GCS': 'GCS'})
list(df)

3983


['tid',
 'hosp_date',
 'age',
 'gender',
 'Levels',
 'icd_code',
 'trauma_type',
 'physical_abuse',
 'Injury Comments',
 'airbag_deploy',
 'patient_pos',
 'safety_equip_issues',
 'child_restraint',
 'mv_speed',
 'fall_height',
 'transport_type',
 'transport_mode',
 'Field SBP',
 'Field HR',
 'Shock Index',
 'Field RR',
 'resp_assis',
 'RTS',
 'GCS',
 'arrived_from',
 'ED_LOS',
 'disposition',
 'ED_SBP',
 'ED_HR',
 'ED_RR',
 'ED_GCS',
 'total_vent_days',
 'days_in_icu',
 'hosp_LOS',
 'total_LOS',
 'time_to_first_OR',
 'death',
 'discharge_dispo',
 'injury_score',
 'AIS',
 'AIS_2005']

In [3]:
df.head()

tid   hosp_date age gender Levels  \
0  18131  2016-01-01  16      M      N   
1  18132  2016-01-01  14      F      1   
2  18133  2016-01-01   9      M      N   
3  18134  2016-01-01   0      F      N   
4  18135  2016-01-01   2      F      N   

                                            icd_code trauma_type  \
0           DISCHARGE OF FIREWORK, INITIAL ENCOUNTER        Burn   
1                ASSAULT BY KNIFE, INITIAL ENCOUNTER  Penetratin   
2  PEDESTRIAN ON FOOT INJURED IN COLLISION WITH C...       Blunt   
3       FALL FROM OTHER FURNITURE, INITIAL ENCOUNTER       Blunt   
4  OTHER FALL FROM ONE LEVEL TO ANOTHER, INITIAL ...       Blunt   

  physical_abuse                                    Injury Comments  \
0              N  M presenting today with eye injury. Pt celebra...   
1              N  female who was at a party in Casa Grande last ...   
2              N  male with no sig PMH who presents via EMS with...   
3              N  36 week premie who presents after patient fell...   
4              N  F with no significant past medical history pre...   

  airbag_deploy   ...    total_vent_days days_in_icu hosp_LOS total_LOS  \
0           *NA   ...                *NA         *NA        1      0.68   
1           *NA   ...                *NA         *NA      *NA      0.31   
2           *NA   ...                *NA         *NA      *NA      0.24   
3           *NA   ...                *NA         *NA      *NA      0.09   
4           *NA   ...                *NA         *NA        1      0.89   

  time_to_first_OR death                 discharge_dispo injury_score  \
0              *BL     L  Discharged home with no home s          2.0   
1              *BL     L                             *NA          2.0   
2              *NA     L                             *NA          1.0   
3              *BL     L                             *NA          0.0   
4              710     L  Discharged home with no home s          4.0   

          AIS AIS_2005  
0  240603\r\n      NaN  
1  210602\r\n      NaN  
2  810402\r\n      NaN  
3  100099\r\n      NaN  
4  751351\r\n      NaN  

[5 rows x 41 columns]

In [4]:
# Visualize the sbp and rr columns
def coerce_df_columns_to_numeric(df, column_list):
    df[column_list] = df[column_list].apply(pd.to_numeric, errors='coerce')

# Convert t1, and sbp/rr to numeric. Int if possible.
# Note: RR and SBP cannot be converted to int atm since they may have na's
coerce_df_columns_to_numeric(df, ['tid', 'Field SBP', 'Field RR'])

# Get a subset of the dataframe to visualize our desired columns
df_sbprr_subset = pd.DataFrame(df, columns = ['tid', 'Field SBP', 'Field RR'])
df_sbprr_subset.head()

tid  Field SBP  Field RR
0  18131.0        0.0       0.0
1  18132.0      108.0      78.0
2  18133.0        0.0       0.0
3  18134.0     9999.0      24.0
4  18135.0        0.0      28.0

In [5]:
# See unique SBP fields. Quick visualization for nulls.
# Safe to assume Assuming that sbf fields are positive integers in a small range.
init_sbp_arr = np.sort(df['Field SBP'].unique())
init_sbp_arr

array([    0.,    49.,    58.,    63.,    64.,    67.,    69.,    70.,
          71.,    72.,    73.,    74.,    75.,    76.,    77.,    78.,
          79.,    80.,    81.,    82.,    83.,    84.,    85.,    86.,
          87.,    88.,    89.,    90.,    91.,    92.,    93.,    94.,
          95.,    96.,    97.,    98.,    99.,   100.,   101.,   102.,
         103.,   104.,   105.,   106.,   107.,   108.,   109.,   110.,
         111.,   112.,   113.,   114.,   115.,   116.,   117.,   118.,
         119.,   120.,   121.,   122.,   123.,   124.,   125.,   126.,
         127.,   128.,   129.,   130.,   131.,   132.,   133.,   134.,
         135.,   136.,   137.,   138.,   139.,   140.,   141.,   142.,
         143.,   144.,   145.,   146.,   147.,   148.,   149.,   150.,
         151.,   152.,   154.,   155.,   156.,   157.,   158.,   159.,
         160.,   162.,   163.,   165.,   166.,   167.,   168.,   169.,
         170.,   171.,   174.,   180.,   187.,   220.,   378.,   408.,
      

In [6]:
# See unique RR fields. Same reasoning as SBP fields
init_rr_arr = np.sort(df['Field RR'].unique())
init_rr_arr

array([  0.00000000e+00,   7.00000000e+00,   8.00000000e+00,
         1.00000000e+01,   1.10000000e+01,   1.20000000e+01,
         1.30000000e+01,   1.40000000e+01,   1.50000000e+01,
         1.60000000e+01,   1.70000000e+01,   1.80000000e+01,
         1.90000000e+01,   2.00000000e+01,   2.10000000e+01,
         2.20000000e+01,   2.30000000e+01,   2.40000000e+01,
         2.50000000e+01,   2.60000000e+01,   2.70000000e+01,
         2.80000000e+01,   2.90000000e+01,   3.00000000e+01,
         3.10000000e+01,   3.20000000e+01,   3.30000000e+01,
         3.40000000e+01,   3.50000000e+01,   3.60000000e+01,
         3.70000000e+01,   3.80000000e+01,   3.90000000e+01,
         4.00000000e+01,   4.10000000e+01,   4.20000000e+01,
         4.30000000e+01,   4.40000000e+01,   4.50000000e+01,
         4.60000000e+01,   4.70000000e+01,   4.80000000e+01,
         5.00000000e+01,   5.20000000e+01,   5.40000000e+01,
         5.50000000e+01,   6.00000000e+01,   7.80000000e+01,
         1.04000000e+02,

In [12]:
# Respiratory rate subset
rr_subset = df
rr_subset = rr_subset.dropna(subset=['Field RR'])
rr_subset = rr_subset.ix[(rr_subset['Field RR']> 0) & (rr_subset['Field RR'] != 9999)]
#Test that sbp doesn't have nan
final_rr_arr = np.sort(rr_subset['Field RR'].unique().astype(int))
final_rr_arr

array([  7,   8,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,
        21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
        34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,
        47,  48,  50,  52,  54,  55,  60,  78, 104, 124, 165])

In [14]:
# SBP subset
sbp_subset = df
sbp_subset = sbp_subset.dropna(subset=['Field SBP'])
sbp_subset = sbp_subset.ix[(sbp_subset['Field SBP']> 0) & (rr_subset['Field SBP'] != 9999)]
#Test that sbp doesn't have nan
final_sbp_arr = np.sort(sbp_subset['Field SBP'].unique().astype(int))
final_sbp_arr

array([ 49,  58,  63,  64,  67,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
       116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
       129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
       142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 154, 155,
       156, 157, 158, 159, 160, 162, 163, 165, 166, 167, 168, 169, 170,
       171, 174, 180, 187, 220, 378, 408])

In [40]:
# See how many rows were dropped when removing nan rr's and nan sbp's
df_count = df.shape[0]
rr_count = rr_subset.shape[0]
sbp_count = sbp_subset.shape[0]
missing_rr_count = df_count - rr_count
missing_sbp_count = df_count - sbp_count
print('Missing Data Analysis:')
print('Clean rows- Rows without 0, nan, 9999, or other null values for SBP/RR')
print('# of df rows:', df_count)
print('# of valid rr rows:', rr_count)
print('# of valid sbp rows:', sbp_count)
print('# of invalid rr rows:', missing_rr_count)
print('# of invalid sbp rows:', missing_sbp_count)
print('percentage of invalid rr rows: {0:.3f}%'.format(100 * missing_rr_count / df_count))
print('percentage of invalid sbp rows: {0:.3f}%'.format(100 * missing_sbp_count / df_count))

# High, low, healthy groups.. SBP: < 120, 120-140, >140   RR: < 12, 12-20, >20... For each group, determine % of lvl 1 and 2
# Different groups.. level of patients in normal group, low sbp: high/low rr, high sbp: high/low rr (include normals?)

def rows_in_range(data_frame, column_name, low_limit, high_limit):
    low_range = data_frame.ix[(data_frame[column_name] < low_limit)]
    norm_range = data_frame.ix[(data_frame[column_name] >= low_limit) & (data_frame[column_name] <= high_limit)]
    high_range = data_frame.ix[(data_frame[column_name] > high_limit)]
    return [low_range, norm_range, high_range]

def print_subset_analysis(subset_range_arr, column_alias):
    low_range = subset_range_arr[0]
    norm_range = subset_range_arr[1]
    high_range = subset_range_arr[2]
    # Refactoring needed if this has to be expanded. for loop object or 2d array.(low priority since this is for a one time alaysis report)
    low_range_one = low_range[low_range['Levels'].isin(['1'])].shape[0]
    low_range_two = low_range[low_range['Levels'].isin(['2'])].shape[0]
    norm_range_one = norm_range[norm_range['Levels'].isin(['1'])].shape[0]
    norm_range_two = norm_range[norm_range['Levels'].isin(['2'])].shape[0]
    high_range_one = high_range[high_range['Levels'].isin(['1'])].shape[0]
    high_range_two = high_range[high_range['Levels'].isin(['2'])].shape[0]
    # Total # of patients in any category. Note: They have to be either high, normal, or medium.
    total_one = low_range_one + norm_range_one + high_range_one
    total_two = low_range_two + norm_range_two + high_range_two
    print('\n\n', column_alias, 'analysis')
    print('# of', column_alias, 'rows in the following categories: low-', low_range.shape[0], 'norm-', norm_range.shape[0], 'high-', high_range.shape[0])
    print('low', column_alias ,'patients that have level 1 trauma: ', low_range_one, '({0:.3f}%)'.format(100 * low_range_one / low_range.shape[0]))
    print('low', column_alias ,'patients that have level 2 trauma: ', low_range_two, '({0:.3f}%)'.format(100 * low_range_two / low_range.shape[0]))
    print('normal', column_alias ,'patients that have level 1 trauma: ', norm_range_one, '({0:.3f}%)'.format(100 * norm_range_one / norm_range.shape[0]))
    print('normal', column_alias ,'patients that have level 2 trauma: ', norm_range_two, '({0:.3f}%)'.format(100 * norm_range_two / norm_range.shape[0]))
    print('high', column_alias ,'patients that have level 1 trauma: ', high_range_one, '({0:.3f}%)'.format(100 * high_range_one / high_range.shape[0]))
    print('high', column_alias ,'patients that have level 2 trauma: ', high_range_two, '({0:.3f}%)'.format(100 * high_range_two / high_range.shape[0]))
    
    print('% of level 1 patients that have a', column_alias, 
          ' in a range that is: low: {0:.3f}%,'.format(100 * low_range_one / total_one), 
          'normal- {0:.3f}%,'.format(100 * norm_range_one / total_one), 
          'high- {0:.3f}%'.format(100 * high_range_one / total_one))
    print('% of level 2 patients that have a', column_alias, 
      ' in a range that is: low: {0:.3f}%,'.format(100 * low_range_two / total_two), 
      'normal- {0:.3f}%,'.format(100 * norm_range_two / total_two), 
      'high- {0:.3f}%'.format(100 * high_range_two / total_two))

    
sbp_range = rows_in_range(sbp_subset, 'Field SBP', 120, 140)
rr_range = rows_in_range(rr_subset, 'Field RR', 12, 20)
print_subset_analysis(sbp_range, 'SBP')
print_subset_analysis(rr_range, 'RR')


Missing Data Analysis:
Clean rows- Rows without 0, nan, 9999, or other null values for SBP/RR
# of df rows: 3983
# of valid rr rows: 2564
# of valid sbp rows: 2260
# of invalid rr rows: 1419
# of invalid sbp rows: 1723
percentage of invalid rr rows: 35.626%
percentage of invalid sbp rows: 43.259%


 SBP analysis
# of SBP rows in the following categories: low- 1216 norm- 837 high- 207
low SBP patients that have level 1 trauma:  100 (8.224%)
low SBP patients that have level 2 trauma:  346 (28.454%)
normal SBP patients that have level 1 trauma:  59 (7.049%)
normal SBP patients that have level 2 trauma:  238 (28.435%)
high SBP patients that have level 1 trauma:  16 (7.729%)
high SBP patients that have level 2 trauma:  55 (26.570%)
% of level 1 patients that have a SBP  in a range that is: low: 57.143%, normal- 33.714%, high- 9.143%
% of level 2 patients that have a SBP  in a range that is: low: 54.147%, normal- 37.246%, high- 8.607%


 RR analysis
# of RR rows in the following categories: 

In [ ]:
# RR subset, showing sbp and rr (note, sbp can be null/0)
pd.DataFrame(rr_subset, columns = ['T1#', 'Field SBP', 'Field RR'])

In [ ]:
# RR subset, showing sbp and rr (note, rr can be null/0)
pd.DataFrame(sbp_subset, columns = ['T1#', 'Field SBP', 'Field RR'])

In [ ]:
# Download Respiratory Rate and Systolic Blood Pressure subsets as csv files
rr_subset.to_csv('./rr_subset.csv')
sbp_subset.to_csv('./sbp_subset.csv', encoding='utf-8', index=False)